


development:
   adapter: mysql2
   database: API_development
   username: nazim
   password: nazim 
   host: localhost

# test:
#   adapter: mysql2
#   database: API_test
#   username: nazim
#   password: nazim
#   host: localhost
   
# production:
#   adapter: mysql2
#   database: API_production
#   username: nazim
#   password: nazim
#   host: localhost
